remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

title: PowerShell Reference
description: A growing library of PowerShell tools and patterns I've put together as a sysadmin. Public and open-source for anyone who wants to learn, copy, or contribute.
